using JiewStore.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using JiewStore.DAL;

namespace JiewStore.Controllers
{
    public static class CustomerHelper
    {
        //since Customer class was generated by EF frame work
        //so instead of modify by add specific constructor
        //i decided to make helper function
        public static Customer NewCustomer(string nickName, string fullName, string facebook, string phone, DateTime birthDate, string address) {
            
            var newCustomer = new Customer() {
                NickName = nickName,
                FullName = fullName,
                Facebook = facebook,
                Phone = phone,
                BirthDate = birthDate,
                Address = address
            };

            return newCustomer;
        }

    }
}