//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiewStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime RecordTime { get; set; }
        public int Point { get; set; }
        public float Amount { get; set; }
        public float PointPerAmount { get; set; }
        public float PointMultiplier { get; set; }
        public string Remark { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
